services:
  # 실행할 서비스 정의
  postgres:
    # 임의
    image: postgres:15-alpine
    restart: always
    # volumes: 도커를 종료하면 그 이미지 안에 존재했던 파일들이 날아감
    # hostOS의 볼륨과 매핑하는 작업
    # hostOS:이미지 안에 존재하는 위치
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      #hostOS port:image port
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
