# Generated by Django 4.0.4 on 2022-04-30 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=50)),
                ('userEmail', models.CharField(max_length=100)),
                ('userPwd', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('createDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
